### ISSUE TITLE
Not able to fetch the css files on installing the module.

### ISSUE THREAD

**Issue by Akshay-Choudhary** [samrith-s/react-select-input#1]
I did not see the css file in the node modules folder for react-select-input upon installation.

**Comment by samrith-s** [comment]
Hey @Akshay-Choudhary, thanks for noticing that! Please upgrade to `v1.0.0` and you should find the CSS file in `lib/`. 

Let me know if it works!

**Comment by samrith-s** [comment]
@Akshay-Choudhary You can just override the CSS in your custom stylesheet.

For example, you could do something like:
```css
@import 'react-select-input/lib/react-select-input.css';

/* override react-select-input CSS with your custom styles */
```
